# Generated by Django 3.1.7 on 2021-03-28 18:21

from django.db import migrations, models
import rest_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=rest_app.models.upload_status_image),
        ),
        migrations.AlterField(
            model_name='status',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
