# Generated by Django 3.1.7 on 2021-03-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0002_auto_20210329_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
